{% set name = "libsecp256k1-py-bindings" %}
{% set version = "0.4.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/MementoRC/libsecp256k1-py-bindings/archive/refs/tags/v{{ version }}.tar.gz
  sha256: facbc0d35df65eaa7cc999edce08ba3cfd84fa4ff690da1271357f8f4c119155

build:
  number: 3
  script:  {{ PYTHON }} -m pip install . --use-pep517 -vvv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - cffi >=1.3.0
    - libsecp256k1
    - pip
    - pkgconfig
    - python
  run:
    - asn1crypto
    - {{ pin_compatible('cffi') }}
    - python

test:
  imports:
    - libsecp256k1_py_bindings
  source_files:
    - tests/
  requires:
    - pip
    - pytest
    - pytest-benchmark
  commands:
    - pip check
    - pytest -v tests

about:
  home: https://github.com/MementoRC/{{ name }}
  summary: Cross-platform Python CFFI bindings for libsecp256k1 (CFFI from Coincurve)
  doc_url: https://ofek.dev/coincurve/
  description: |
    This library provides well-tested Python bindings for libsecp256k1,
    the heavily optimized C library used by Bitcoin Core for operations
    on the elliptic curve secp256k1. It is a streamlined version of Coincurve
  license: MIT OR Apache-2.0
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE

extra:
  recipe-maintainers:
    - ofek
    - MementoRC
